//
//  GUI_ButtonFontAwesome.hpp
//  FontWorks
//
//  Created by SIHARAT THAMMAYA on 12/31/2559 BE.
//  Copyright © 2559 Jimmy Software Co., Ltd. All rights reserved.
//

#ifndef GUI_ButtonFontAwesome_hpp
#define GUI_ButtonFontAwesome_hpp

#include <stdio.h>
#include <SDL.h>
#include "SDL_gui.h"

// Variables
// __________________________

//@fa_font_path:        "../fontsu             
//@fa_font_size_base:   14px             
//@fa_line_height_base: 1             
////@fa_font_path:        "//netdna.bootstrapcdn.com/font_awesome/4.7.0/fontsu              // for referencing Bootstrap CDN font files directly
//@fa_css_prefix:       fa             
//@fa_version:          "4.7.0u             
//@fa_border_color:     #eee             
//@fa_inverse:          #fff             
//@fa_li_width:         (30em / 14)

// __________________________
// End css header

// download from url http://fontawesome.io/assets/font-awesome-4.7.0.zip
#define kFont_awesome_path                          "data/fontawesome-webfont.ttf"

#define kDefault_font_size                          16
#define kNormal_icon_size                           18

// S, M, L
#define kSmall_icon_size                            kDefault_font_size
#define kMedium_icon_size                           kNormal_icon_size
#define kLarge_icon_size                            24

#define kIcon_500px                                 0xf26eu
#define kIcon_address_book                          0xf2b9u
#define kIcon_address_book_o                        0xf2bau
#define kIcon_address_card                          0xf2bbu
#define kIcon_address_card_o                        0xf2bcu
#define kIcon_adjust                                0xf042u
#define kIcon_adn                                   0xf170u
#define kIcon_align_center                          0xf037u
#define kIcon_align_justify                         0xf039u
#define kIcon_align_left                            0xf036u
#define kIcon_align_right                           0xf038u
#define kIcon_amazon                                0xf270u
#define kIcon_ambulance                             0xf0f9u
#define kIcon_american_sign_language_interpreting   0xf2a3u
#define kIcon_anchor                                0xf13du
#define kIcon_android                               0xf17bu
#define kIcon_angellist                             0xf209u
#define kIcon_angle_double_down                     0xf103u
#define kIcon_angle_double_left                     0xf100u
#define kIcon_angle_double_right                    0xf101u
#define kIcon_angle_double_up                       0xf102u
#define kIcon_angle_down                            0xf107u
#define kIcon_angle_left                            0xf104u
#define kIcon_angle_right                           0xf105u
#define kIcon_angle_up                              0xf106u
#define kIcon_apple                                 0xf179u
#define kIcon_archive                               0xf187u
#define kIcon_area_chart                            0xf1feu
#define kIcon_arrow_circle_down                     0xf0abu
#define kIcon_arrow_circle_left                     0xf0a8u
#define kIcon_arrow_circle_o_down                   0xf01au
#define kIcon_arrow_circle_o_left                   0xf190u
#define kIcon_arrow_circle_o_right                  0xf18eu
#define kIcon_arrow_circle_o_up                     0xf01bu
#define kIcon_arrow_circle_right                    0xf0a9u
#define kIcon_arrow_circle_up                       0xf0aau
#define kIcon_arrow_down                            0xf063u
#define kIcon_arrow_left                            0xf060u
#define kIcon_arrow_right                           0xf061u
#define kIcon_arrow_up                              0xf062u
#define kIcon_arrows                                0xf047u
#define kIcon_arrows_alt                            0xf0b2u
#define kIcon_arrows_h                              0xf07eu
#define kIcon_arrows_v                              0xf07du
#define kIcon_asl_interpreting                      0xf2a3u
#define kIcon_assistive_listening_systems           0xf2a2u
#define kIcon_asterisk                              0xf069u
#define kIcon_at                                    0xf1fau
#define kIcon_audio_description                     0xf29eu
#define kIcon_automobile                            0xf1b9u
#define kIcon_backward                              0xf04au
#define kIcon_balance_scale							0xf24eu
#define kIcon_ban									0xf05eu
#define kIcon_bandcamp								0xf2d5u
#define kIcon_bank									0xf19cu
#define kIcon_bar_chart								0xf080u
#define kIcon_bar_chart_o							0xf080u
#define kIcon_barcode								0xf02au
#define kIcon_bars									0xf0c9u
#define kIcon_bath									0xf2cdu
#define kIcon_bathtub								0xf2cdu
#define kIcon_battery								0xf240u
#define kIcon_battery_0								0xf244u
#define kIcon_battery_1								0xf243u
#define kIcon_battery_2								0xf242u
#define kIcon_battery_3								0xf241u
#define kIcon_battery_4								0xf240u
#define kIcon_battery_empty							0xf244u
#define kIcon_battery_full							0xf240u
#define kIcon_battery_half							0xf242u
#define kIcon_battery_quarter						0xf243u
#define kIcon_battery_three_quarters				0xf241u
#define kIcon_bed									0xf236u
#define kIcon_beer									0xf0fcu
#define kIcon_behance								0xf1b4u
#define kIcon_behance_square						0xf1b5u
#define kIcon_bell									0xf0f3u
#define kIcon_bell_o								0xf0a2u
#define kIcon_bell_slash							0xf1f6u
#define kIcon_bell_slash_o							0xf1f7u
#define kIcon_bicycle								0xf206u
#define kIcon_binoculars							0xf1e5u
#define kIcon_birthday_cake							0xf1fdu
#define kIcon_bitbucket								0xf171u
#define kIcon_bitbucket_square						0xf172u
#define kIcon_bitcoin								0xf15au
#define kIcon_black_tie								0xf27eu
#define kIcon_blind									0xf29du
#define kIcon_bluetooth								0xf293u
#define kIcon_bluetooth_b							0xf294u
#define kIcon_bold									0xf032u
#define kIcon_bolt									0xf0e7u
#define kIcon_bomb									0xf1e2u
#define kIcon_book									0xf02du
#define kIcon_bookmark								0xf02eu
#define kIcon_bookmark_o							0xf097u
#define kIcon_braille								0xf2a1u
#define kIcon_briefcase								0xf0b1u
#define kIcon_btc									0xf15au
#define kIcon_bug									0xf188u
#define kIcon_building								0xf1adu
#define kIcon_building_o							0xf0f7u
#define kIcon_bullhorn								0xf0a1u
#define kIcon_bullseye								0xf140u
#define kIcon_bus									0xf207u
#define kIcon_buysellads							0xf20du
#define kIcon_cab									0xf1bau
#define kIcon_calculator							0xf1ecu
#define kIcon_calendar								0xf073u
#define kIcon_calendar_check_o						0xf274u
#define kIcon_calendar_minus_o						0xf272u
#define kIcon_calendar_o							0xf133u
#define kIcon_calendar_plus_o						0xf271u
#define kIcon_calendar_times_o						0xf273u
#define kIcon_camera								0xf030u
#define kIcon_camera_retro							0xf083u
#define kIcon_car									0xf1b9u
#define kIcon_caret_down							0xf0d7u
#define kIcon_caret_left							0xf0d9u
#define kIcon_caret_right							0xf0dau
#define kIcon_caret_square_o_down					0xf150u
#define kIcon_caret_square_o_left					0xf191u
#define kIcon_caret_square_o_right					0xf152u
#define kIcon_caret_square_o_up						0xf151u
#define kIcon_caret_up								0xf0d8u
#define kIcon_cart_arrow_down						0xf218u
#define kIcon_cart_plus								0xf217u
#define kIcon_cc									0xf20au
#define kIcon_cc_amex								0xf1f3u
#define kIcon_cc_diners_club						0xf24cu
#define kIcon_cc_discover							0xf1f2u
#define kIcon_cc_jcb								0xf24bu
#define kIcon_cc_mastercard							0xf1f1u
#define kIcon_cc_paypal								0xf1f4u
#define kIcon_cc_stripe								0xf1f5u
#define kIcon_cc_visa								0xf1f0u
#define kIcon_certificate							0xf0a3u
#define kIcon_chain									0xf0c1u
#define kIcon_chain_broken							0xf127u
#define kIcon_check									0xf00cu
#define kIcon_check_circle							0xf058u
#define kIcon_check_circle_o						0xf05du
#define kIcon_check_square							0xf14au
#define kIcon_check_square_o						0xf046u
#define kIcon_chevron_circle_down					0xf13au
#define kIcon_chevron_circle_left					0xf137u
#define kIcon_chevron_circle_right					0xf138u
#define kIcon_chevron_circle_up						0xf139u
#define kIcon_chevron_down							0xf078u
#define kIcon_chevron_left							0xf053u
#define kIcon_chevron_right							0xf054u
#define kIcon_chevron_up							0xf077u
#define kIcon_child									0xf1aeu
#define kIcon_chrome								0xf268u
#define kIcon_circle								0xf111u
#define kIcon_circle_o								0xf10cu
#define kIcon_circle_o_notch						0xf1ceu
#define kIcon_circle_thin							0xf1dbu
#define kIcon_clipboard								0xf0eau
#define kIcon_clock_o								0xf017u
#define kIcon_clone									0xf24du
#define kIcon_close									0xf00du
#define kIcon_cloud									0xf0c2u
#define kIcon_cloud_download						0xf0edu
#define kIcon_cloud_upload							0xf0eeu
#define kIcon_cny									0xf157u
#define kIcon_code									0xf121u
#define kIcon_code_fork								0xf126u
#define kIcon_codepen								0xf1cbu
#define kIcon_codiepie								0xf284u
#define kIcon_coffee								0xf0f4u
#define kIcon_cog									0xf013u
#define kIcon_cogs									0xf085u
#define kIcon_columns								0xf0dbu
#define kIcon_comment								0xf075u
#define kIcon_comment_o								0xf0e5u
#define kIcon_commenting							0xf27au
#define kIcon_commenting_o							0xf27bu
#define kIcon_comments								0xf086u
#define kIcon_comments_o							0xf0e6u
#define kIcon_compass								0xf14eu
#define kIcon_compress								0xf066u
#define kIcon_connectdevelop						0xf20eu
#define kIcon_contao								0xf26du
#define kIcon_copy									0xf0c5u
#define kIcon_copyright								0xf1f9u
#define kIcon_creative_commons						0xf25eu
#define kIcon_credit_card							0xf09du
#define kIcon_credit_card_alt						0xf283u
#define kIcon_crop									0xf125u
#define kIcon_crosshairs							0xf05bu
#define kIcon_css3									0xf13cu
#define kIcon_cube									0xf1b2u
#define kIcon_cubes									0xf1b3u
#define kIcon_cut									0xf0c4u
#define kIcon_cutlery								0xf0f5u
#define kIcon_dashboard								0xf0e4u
#define kIcon_dashcube								0xf210u
#define kIcon_database								0xf1c0u
#define kIcon_deaf									0xf2a4u
#define kIcon_deafness								0xf2a4u
#define kIcon_dedent								0xf03bu
#define kIcon_delicious								0xf1a5u
#define kIcon_desktop								0xf108u
#define kIcon_deviantart							0xf1bdu
#define kIcon_diamond								0xf219u
#define kIcon_digg									0xf1a6u
#define kIcon_dollar								0xf155u
#define kIcon_dot_circle_o							0xf192u
#define kIcon_download								0xf019u
#define kIcon_dribbble								0xf17du
#define kIcon_drivers_license						0xf2c2u
#define kIcon_drivers_license_o						0xf2c3u
#define kIcon_dropbox								0xf16bu
#define kIcon_drupal								0xf1a9u
#define kIcon_edge									0xf282u
#define kIcon_edit									0xf044u
#define kIcon_eercast								0xf2dau
#define kIcon_eject									0xf052u
#define kIcon_ellipsis_h							0xf141u
#define kIcon_ellipsis_v							0xf142u
#define kIcon_empire								0xf1d1u
#define kIcon_envelope								0xf0e0u
#define kIcon_envelope_o							0xf003u
#define kIcon_envelope_open							0xf2b6u
#define kIcon_envelope_open_o						0xf2b7u
#define kIcon_envelope_square						0xf199u
#define kIcon_envira								0xf299u
#define kIcon_eraser								0xf12du
#define kIcon_etsy									0xf2d7u
#define kIcon_eur									0xf153u
#define kIcon_euro									0xf153u
#define kIcon_exchange								0xf0ecu
#define kIcon_exclamation							0xf12au
#define kIcon_exclamation_circle					0xf06au
#define kIcon_exclamation_triangle					0xf071u
#define kIcon_expand								0xf065u
#define kIcon_expeditedssl							0xf23eu
#define kIcon_external_link							0xf08eu
#define kIcon_external_link_square					0xf14cu
#define kIcon_eye									0xf06eu
#define kIcon_eye_slash								0xf070u
#define kIcon_eyedropper							0xf1fbu
#define kIcon_fa									0xf2b4u
#define kIcon_facebook								0xf09au
#define kIcon_facebook_f							0xf09au
#define kIcon_facebook_official						0xf230u
#define kIcon_facebook_square						0xf082u
#define kIcon_fast_backward							0xf049u
#define kIcon_fast_forward							0xf050u
#define kIcon_fax									0xf1acu
#define kIcon_feed									0xf09eu
#define kIcon_female								0xf182u
#define kIcon_fighter_jet							0xf0fbu
#define kIcon_file									0xf15bu
#define kIcon_file_archive_o						0xf1c6u
#define kIcon_file_audio_o							0xf1c7u
#define kIcon_file_code_o							0xf1c9u
#define kIcon_file_excel_o							0xf1c3u
#define kIcon_file_image_o							0xf1c5u
#define kIcon_file_movie_o							0xf1c8u
#define kIcon_file_o								0xf016u
#define kIcon_file_pdf_o							0xf1c1u
#define kIcon_file_photo_o							0xf1c5u
#define kIcon_file_picture_o						0xf1c5u
#define kIcon_file_powerpoint_o						0xf1c4u
#define kIcon_file_sound_o							0xf1c7u
#define kIcon_file_text								0xf15cu
#define kIcon_file_text_o							0xf0f6u
#define kIcon_file_video_o							0xf1c8u
#define kIcon_file_word_o							0xf1c2u
#define kIcon_file_zip_o							0xf1c6u
#define kIcon_files_o								0xf0c5u
#define kIcon_film									0xf008u
#define kIcon_filter								0xf0b0u
#define kIcon_fire									0xf06du
#define kIcon_fire_extinguisher						0xf134u
#define kIcon_firefox								0xf269u
#define kIcon_first_order							0xf2b0u
#define kIcon_flag									0xf024u
#define kIcon_flag_checkered						0xf11eu
#define kIcon_flag_o								0xf11du
#define kIcon_flash									0xf0e7u
#define kIcon_flask									0xf0c3u
#define kIcon_flickr								0xf16eu
#define kIcon_floppy_o								0xf0c7u
#define kIcon_folder								0xf07bu
#define kIcon_folder_o								0xf114u
#define kIcon_folder_open							0xf07cu
#define kIcon_folder_open_o							0xf115u
#define kIcon_font									0xf031u
#define kIcon_font_awesome							0xf2b4u
#define kIcon_fonticons								0xf280u
#define kIcon_fort_awesome							0xf286u
#define kIcon_forumbee								0xf211u
#define kIcon_forward								0xf04eu
#define kIcon_foursquare							0xf180u
#define kIcon_free_code_camp						0xf2c5u
#define kIcon_frown_o								0xf119u
#define kIcon_futbol_o								0xf1e3u
#define kIcon_gamepad								0xf11bu
#define kIcon_gavel									0xf0e3u
#define kIcon_gbp									0xf154u
#define kIcon_ge									0xf1d1u
#define kIcon_gear									0xf013u
#define kIcon_gears									0xf085u
#define kIcon_genderless							0xf22du
#define kIcon_get_pocket							0xf265u
#define kIcon_gg									0xf260u
#define kIcon_gg_circle								0xf261u
#define kIcon_gift									0xf06bu
#define kIcon_git									0xf1d3u
#define kIcon_git_square							0xf1d2u
#define kIcon_github								0xf09bu
#define kIcon_github_alt							0xf113u
#define kIcon_github_square							0xf092u
#define kIcon_gitlab								0xf296u
#define kIcon_gittip								0xf184u
#define kIcon_glass									0xf000u
#define kIcon_glide									0xf2a5u
#define kIcon_glide_g								0xf2a6u
#define kIcon_globe									0xf0acu
#define kIcon_google								0xf1a0u
#define kIcon_google_plus							0xf0d5u
#define kIcon_google_plus_circle				    0xf2b3u
#define kIcon_google_plus_official				    0xf2b3u
#define kIcon_google_plus_square				    0xf0d4u
#define kIcon_google_wallet							0xf1eeu
#define kIcon_graduation_cap				        0xf19du
#define kIcon_gratipay								0xf184u
#define kIcon_grav									0xf2d6u
#define kIcon_group									0xf0c0u
#define kIcon_h_square								0xf0fdu
#define kIcon_hacker_news							0xf1d4u
#define kIcon_hand_grab_o							0xf255u
#define kIcon_hand_lizard_o							0xf258u
#define kIcon_hand_o_down							0xf0a7u
#define kIcon_hand_o_left							0xf0a5u
#define kIcon_hand_o_right							0xf0a4u
#define kIcon_hand_o_up								0xf0a6u
#define kIcon_hand_paper_o							0xf256u
#define kIcon_hand_peace_o							0xf25bu
#define kIcon_hand_pointer_o				        0xf25au
#define kIcon_hand_rock_o							0xf255u
#define kIcon_hand_scissors_o				        0xf257u
#define kIcon_hand_spock_o							0xf259u
#define kIcon_hand_stop_o							0xf256u
#define kIcon_handshake_o							0xf2b5u
#define kIcon_hard_of_hearing			        	0xf2a4u
#define kIcon_hashtag								0xf292u
#define kIcon_hdd_o									0xf0a0u
#define kIcon_header								0xf1dcu
#define kIcon_headphones							0xf025u
#define kIcon_heart									0xf004u
#define kIcon_heart_o								0xf08au
#define kIcon_heartbeat								0xf21eu
#define kIcon_history								0xf1dau
#define kIcon_home									0xf015u
#define kIcon_hospital_o							0xf0f8u
#define kIcon_hotel									0xf236u
#define kIcon_hourglass								0xf254u
#define kIcon_hourglass_1							0xf251u
#define kIcon_hourglass_2							0xf252u
#define kIcon_hourglass_3							0xf253u
#define kIcon_hourglass_end							0xf253u
#define kIcon_hourglass_half				        0xf252u
#define kIcon_hourglass_o							0xf250u
#define kIcon_hourglass_start			        	0xf251u
#define kIcon_houzz									0xf27cu
#define kIcon_html5									0xf13bu
#define kIcon_i_cursor								0xf246u
#define kIcon_id_badge								0xf2c1u
#define kIcon_id_card								0xf2c2u
#define kIcon_id_card_o								0xf2c3u
#define kIcon_ils									0xf20bu
#define kIcon_image									0xf03eu
#define kIcon_imdb									0xf2d8u
#define kIcon_inbox									0xf01cu
#define kIcon_indent								0xf03cu
#define kIcon_industry								0xf275u
#define kIcon_info									0xf129u
#define kIcon_info_circle							0xf05au
#define kIcon_inr									0xf156u
#define kIcon_instagram								0xf16du
#define kIcon_institution							0xf19cu
#define kIcon_internet_explorer			        	0xf26bu
#define kIcon_intersex								0xf224u
#define kIcon_ioxhost								0xf208u
#define kIcon_italic								0xf033u
#define kIcon_joomla								0xf1aau
#define kIcon_jpy									0xf157u
#define kIcon_jsfiddle								0xf1ccu
#define kIcon_key									0xf084u
#define kIcon_keyboard_o							0xf11cu
#define kIcon_krw									0xf159u
#define kIcon_language								0xf1abu
#define kIcon_laptop								0xf109u
#define kIcon_lastfm								0xf202u
#define kIcon_lastfm_square							0xf203u
#define kIcon_leaf									0xf06cu
#define kIcon_leanpub								0xf212u
#define kIcon_legal									0xf0e3u
#define kIcon_lemon_o								0xf094u
#define kIcon_level_down							0xf149u
#define kIcon_level_up								0xf148u
#define kIcon_life_bouy								0xf1cdu
#define kIcon_life_buoy								0xf1cdu
#define kIcon_life_ring								0xf1cdu
#define kIcon_life_saver							0xf1cdu
#define kIcon_lightbulb_o							0xf0ebu
#define kIcon_line_chart							0xf201u
#define kIcon_link									0xf0c1u
#define kIcon_linkedin								0xf0e1u
#define kIcon_linkedin_square				        0xf08cu
#define kIcon_linode								0xf2b8u
#define kIcon_linux									0xf17cu
#define kIcon_list									0xf03au
#define kIcon_list_alt								0xf022u
#define kIcon_list_ol								0xf0cbu
#define kIcon_list_ul								0xf0cau
#define kIcon_location_arrow				        0xf124u
#define kIcon_lock									0xf023u
#define kIcon_long_arrow_down				        0xf175u
#define kIcon_long_arrow_left				        0xf177u
#define kIcon_long_arrow_right				        0xf178u
#define kIcon_long_arrow_up							0xf176u
#define kIcon_low_vision							0xf2a8u
#define kIcon_magic									0xf0d0u
#define kIcon_magnet								0xf076u
#define kIcon_mail_forward							0xf064u
#define kIcon_mail_reply							0xf112u
#define kIcon_mail_reply_all				        0xf122u
#define kIcon_male									0xf183u
#define kIcon_map									0xf279u
#define kIcon_map_marker							0xf041u
#define kIcon_map_o									0xf278u
#define kIcon_map_pin								0xf276u
#define kIcon_map_signs								0xf277u
#define kIcon_mars									0xf222u
#define kIcon_mars_double							0xf227u
#define kIcon_mars_stroke							0xf229u
#define kIcon_mars_stroke_h							0xf22bu
#define kIcon_mars_stroke_v							0xf22au
#define kIcon_maxcdn								0xf136u
#define kIcon_meanpath								0xf20cu
#define kIcon_medium								0xf23au
#define kIcon_medkit								0xf0fau
#define kIcon_meetup								0xf2e0u
#define kIcon_meh_o									0xf11au
#define kIcon_mercury								0xf223u
#define kIcon_microchip								0xf2dbu
#define kIcon_microphone							0xf130u
#define kIcon_microphone_slash				        0xf131u
#define kIcon_minus									0xf068u
#define kIcon_minus_circle							0xf056u
#define kIcon_minus_square							0xf146u
#define kIcon_minus_square_o				        0xf147u
#define kIcon_mixcloud								0xf289u
#define kIcon_mobile								0xf10bu
#define kIcon_mobile_phone							0xf10bu
#define kIcon_modx									0xf285u
#define kIcon_money									0xf0d6u
#define kIcon_moon_o								0xf186u
#define kIcon_mortar_board							0xf19du
#define kIcon_motorcycle							0xf21cu
#define kIcon_mouse_pointer							0xf245u
#define kIcon_music									0xf001u
#define kIcon_navicon								0xf0c9u
#define kIcon_neuter								0xf22cu
#define kIcon_newspaper_o							0xf1eau
#define kIcon_object_group							0xf247u
#define kIcon_object_ungroup				        0xf248u
#define kIcon_odnoklassniki							0xf263u
#define kIcon_odnoklassniki_square				    0xf264u
#define kIcon_opencart								0xf23du
#define kIcon_openid								0xf19bu
#define kIcon_opera									0xf26au
#define kIcon_optin_monster							0xf23cu
#define kIcon_outdent								0xf03bu
#define kIcon_pagelines								0xf18cu
#define kIcon_paint_brush							0xf1fcu
#define kIcon_paper_plane							0xf1d8u
#define kIcon_paper_plane_o							0xf1d9u
#define kIcon_paperclip								0xf0c6u
#define kIcon_paragraph								0xf1ddu
#define kIcon_paste									0xf0eau
#define kIcon_pause									0xf04cu
#define kIcon_pause_circle							0xf28bu
#define kIcon_pause_circle_o			        	0xf28cu
#define kIcon_paw									0xf1b0u
#define kIcon_paypal								0xf1edu
#define kIcon_pencil								0xf040u
#define kIcon_pencil_square							0xf14bu
#define kIcon_pencil_square_o			        	0xf044u
#define kIcon_percent								0xf295u
#define kIcon_phone									0xf095u
#define kIcon_phone_square							0xf098u
#define kIcon_photo									0xf03eu
#define kIcon_picture_o								0xf03eu
#define kIcon_pie_chart								0xf200u
#define kIcon_pied_piper							0xf2aeu
#define kIcon_pied_piper_alt				        0xf1a8u
#define kIcon_pied_piper_pp							0xf1a7u
#define kIcon_pinterest								0xf0d2u
#define kIcon_pinterest_p							0xf231u
#define kIcon_pinterest_square				        0xf0d3u
#define kIcon_plane									0xf072u
#define kIcon_play									0xf04bu
#define kIcon_play_circle							0xf144u
#define kIcon_play_circle_o							0xf01du
#define kIcon_plug									0xf1e6u
#define kIcon_plus									0xf067u
#define kIcon_plus_circle							0xf055u
#define kIcon_plus_square							0xf0feu
#define kIcon_plus_square_o							0xf196u
#define kIcon_podcast								0xf2ceu
#define kIcon_power_off								0xf011u
#define kIcon_print									0xf02fu
#define kIcon_product_hunt							0xf288u
#define kIcon_puzzle_piece							0xf12eu
#define kIcon_qq									0xf1d6u
#define kIcon_qrcode								0xf029u
#define kIcon_question								0xf128u
#define kIcon_question_circle				        0xf059u
#define kIcon_question_circle_o				        0xf29cu
#define kIcon_quora									0xf2c4u
#define kIcon_quote_left							0xf10du
#define kIcon_quote_right							0xf10eu
#define kIcon_ra									0xf1d0u
#define kIcon_random								0xf074u
#define kIcon_ravelry								0xf2d9u
#define kIcon_rebel									0xf1d0u
#define kIcon_recycle								0xf1b8u
#define kIcon_reddit								0xf1a1u
#define kIcon_reddit_alien							0xf281u
#define kIcon_reddit_square							0xf1a2u
#define kIcon_refresh								0xf021u
#define kIcon_registered							0xf25du
#define kIcon_remove								0xf00du
#define kIcon_renren								0xf18bu
#define kIcon_reorder								0xf0c9u
#define kIcon_repeat								0xf01eu
#define kIcon_reply									0xf112u
#define kIcon_reply_all								0xf122u
#define kIcon_resistance							0xf1d0u
#define kIcon_retweet								0xf079u
#define kIcon_rmb									0xf157u
#define kIcon_road									0xf018u
#define kIcon_rocket								0xf135u
#define kIcon_rotate_left							0xf0e2u
#define kIcon_rotate_right							0xf01eu
#define kIcon_rouble								0xf158u
#define kIcon_rss									0xf09eu
#define kIcon_rss_square							0xf143u
#define kIcon_rub									0xf158u
#define kIcon_ruble									0xf158u
#define kIcon_rupee									0xf156u
#define kIcon_s15									0xf2cdu
#define kIcon_safari								0xf267u
#define kIcon_save									0xf0c7u
#define kIcon_scissors								0xf0c4u
#define kIcon_scribd								0xf28au
#define kIcon_search								0xf002u
#define kIcon_search_minus							0xf010u
#define kIcon_search_plus							0xf00eu
#define kIcon_sellsy								0xf213u
#define kIcon_send									0xf1d8u
#define kIcon_send_o								0xf1d9u
#define kIcon_server								0xf233u
#define kIcon_share									0xf064u
#define kIcon_share_alt								0xf1e0u
#define kIcon_share_alt_square			        	0xf1e1u
#define kIcon_share_square							0xf14du
#define kIcon_share_square_o			        	0xf045u
#define kIcon_shekel								0xf20bu
#define kIcon_sheqel								0xf20bu
#define kIcon_shield								0xf132u
#define kIcon_ship									0xf21au
#define kIcon_shirtsinbulk							0xf214u
#define kIcon_shopping_bag							0xf290u
#define kIcon_shopping_basket			        	0xf291u
#define kIcon_shopping_cart							0xf07au
#define kIcon_shower								0xf2ccu
#define kIcon_sign_in								0xf090u
#define kIcon_sign_language							0xf2a7u
#define kIcon_sign_out								0xf08bu
#define kIcon_signal								0xf012u
#define kIcon_signing								0xf2a7u
#define kIcon_simplybuilt							0xf215u
#define kIcon_sitemap								0xf0e8u
#define kIcon_skyatlas								0xf216u
#define kIcon_skype									0xf17eu
#define kIcon_slack									0xf198u
#define kIcon_sliders								0xf1deu
#define kIcon_slideshare							0xf1e7u
#define kIcon_smile_o								0xf118u
#define kIcon_snapchat								0xf2abu
#define kIcon_snapchat_ghost			        	0xf2acu
#define kIcon_snapchat_square			        	0xf2adu
#define kIcon_snowflake_o							0xf2dcu
#define kIcon_soccer_ball_o							0xf1e3u
#define kIcon_sort									0xf0dcu
#define kIcon_sort_alpha_asc			        	0xf15du
#define kIcon_sort_alpha_desc			        	0xf15eu
#define kIcon_sort_amount_asc			        	0xf160u
#define kIcon_sort_amount_desc				        0xf161u
#define kIcon_sort_asc								0xf0deu
#define kIcon_sort_desc								0xf0ddu
#define kIcon_sort_down								0xf0ddu
#define kIcon_sort_numeric_asc				        0xf162u
#define kIcon_sort_numeric_desc				        0xf163u
#define kIcon_sort_up								0xf0deu
#define kIcon_soundcloud							0xf1beu
#define kIcon_space_shuttle							0xf197u
#define kIcon_spinner								0xf110u
#define kIcon_spoon									0xf1b1u
#define kIcon_spotify								0xf1bcu
#define kIcon_square								0xf0c8u
#define kIcon_square_o								0xf096u
#define kIcon_stack_exchange				        0xf18du
#define kIcon_stack_overflow			        	0xf16cu
#define kIcon_star									0xf005u
#define kIcon_star_half								0xf089u
#define kIcon_star_half_empty				        0xf123u
#define kIcon_star_half_full				        0xf123u
#define kIcon_star_half_o							0xf123u
#define kIcon_star_o								0xf006u
#define kIcon_steam									0xf1b6u
#define kIcon_steam_square							0xf1b7u
#define kIcon_step_backward							0xf048u
#define kIcon_step_forward							0xf051u
#define kIcon_stethoscope							0xf0f1u
#define kIcon_sticky_note							0xf249u
#define kIcon_sticky_note_o							0xf24au
#define kIcon_stop									0xf04du
#define kIcon_stop_circle							0xf28du
#define kIcon_stop_circle_o							0xf28eu
#define kIcon_street_view							0xf21du
#define kIcon_strikethrough							0xf0ccu
#define kIcon_stumbleupon							0xf1a4u
#define kIcon_stumbleupon_circle			       	0xf1a3u
#define kIcon_subscript								0xf12cu
#define kIcon_subway								0xf239u
#define kIcon_suitcase								0xf0f2u
#define kIcon_sun_o									0xf185u
#define kIcon_superpowers							0xf2ddu
#define kIcon_superscript							0xf12bu
#define kIcon_support								0xf1cdu
#define kIcon_table									0xf0ceu
#define kIcon_tablet								0xf10au
#define kIcon_tachometer							0xf0e4u
#define kIcon_tag									0xf02bu
#define kIcon_tags									0xf02cu
#define kIcon_tasks									0xf0aeu
#define kIcon_taxi									0xf1bau
#define kIcon_telegram								0xf2c6u
#define kIcon_television							0xf26cu
#define kIcon_tencent_weibo							0xf1d5u
#define kIcon_terminal								0xf120u
#define kIcon_text_height							0xf034u
#define kIcon_text_width							0xf035u
#define kIcon_th									0xf00au
#define kIcon_th_large								0xf009u
#define kIcon_th_list								0xf00bu
#define kIcon_themeisle								0xf2b2u
#define kIcon_thermometer							0xf2c7u
#define kIcon_thermometer_0							0xf2cbu
#define kIcon_thermometer_1							0xf2cau
#define kIcon_thermometer_2							0xf2c9u
#define kIcon_thermometer_3							0xf2c8u
#define kIcon_thermometer_4							0xf2c7u
#define kIcon_thermometer_empty			        	0xf2cbu
#define kIcon_thermometer_full			        	0xf2c7u
#define kIcon_thermometer_half			        	0xf2c9u
#define kIcon_thermometer_quarter		        	0xf2cau
#define kIcon_thermometer_three_quarters            0xf2c8u
#define kIcon_thumb_tack                            0xf08du
#define kIcon_thumbs_down                           0xf165u
#define kIcon_thumbs_o_down                         0xf088u
#define kIcon_thumbs_o_up                           0xf087u
#define kIcon_thumbs_up                             0xf164u
#define kIcon_ticket                                0xf145u
#define kIcon_times                                 0xf00du
#define kIcon_times_circle                          0xf057u
#define kIcon_times_circle_o		        		0xf05cu
#define kIcon_times_rectangle		        		0xf2d3u
#define kIcon_times_rectangle_o		        		0xf2d4u
#define kIcon_tint                                  0xf043u
#define kIcon_toggle_down                           0xf150u
#define kIcon_toggle_left                           0xf191u
#define kIcon_toggle_off                            0xf204u
#define kIcon_toggle_on                             0xf205u
#define kIcon_toggle_right                          0xf152u
#define kIcon_toggle_up                             0xf151u
#define kIcon_trademark                             0xf25cu
#define kIcon_train                                 0xf238u
#define kIcon_transgender                           0xf224u
#define kIcon_transgender_alt				        0xf225u
#define kIcon_trash                                 0xf1f8u
#define kIcon_trash_o								0xf014u
#define kIcon_tree									0xf1bbu
#define kIcon_trello								0xf181u
#define kIcon_tripadvisor							0xf262u
#define kIcon_trophy								0xf091u
#define kIcon_truck									0xf0d1u
#define kIcon_try									0xf195u
#define kIcon_tty									0xf1e4u
#define kIcon_tumblr								0xf173u
#define kIcon_tumblr_square							0xf174u
#define kIcon_turkish_lira							0xf195u
#define kIcon_tv									0xf26cu
#define kIcon_twitch								0xf1e8u
#define kIcon_twitter								0xf099u
#define kIcon_twitter_square				        0xf081u
#define kIcon_umbrella								0xf0e9u
#define kIcon_underline								0xf0cdu
#define kIcon_undo									0xf0e2u
#define kIcon_universal_access				        0xf29au
#define kIcon_university							0xf19cu
#define kIcon_unlink								0xf127u
#define kIcon_unlock								0xf09cu
#define kIcon_unlock_alt							0xf13eu
#define kIcon_unsorted								0xf0dcu
#define kIcon_upload								0xf093u
#define kIcon_usb									0xf287u
#define kIcon_usd									0xf155u
#define kIcon_user									0xf007u
#define kIcon_user_circle							0xf2bdu
#define kIcon_user_circle_o							0xf2beu
#define kIcon_user_md								0xf0f0u
#define kIcon_user_o								0xf2c0u
#define kIcon_user_plus								0xf234u
#define kIcon_user_secret							0xf21bu
#define kIcon_user_times							0xf235u
#define kIcon_users          			            0xf0c0u
#define kIcon_vcard           			            0xf2bbu
#define kIcon_vcard_o          			            0xf2bcu
#define kIcon_venus              			        0xf221u
#define kIcon_venus_double							0xf226u
#define kIcon_venus_mars							0xf228u
#define kIcon_viacoin              			        0xf237u
#define kIcon_viadeo                			    0xf2a9u
#define kIcon_viadeo_square							0xf2aau
#define kIcon_video_camera							0xf03du
#define kIcon_vimeo                  			    0xf27du
#define kIcon_vimeo_square							0xf194u
#define kIcon_vine                    			    0xf1cau
#define kIcon_vk			                        0xf189u
#define kIcon_volume_control_phone                  0xf2a0u
#define kIcon_volume_down                           0xf027u
#define kIcon_volume_off                            0xf026u
#define kIcon_volume_up                             0xf028u
#define kIcon_warning                               0xf071u
#define kIcon_wechat                                0xf1d7u
#define kIcon_weibo                                 0xf18au
#define kIcon_weixin                                0xf1d7u
#define kIcon_whatsapp                              0xf232u
#define kIcon_wheelchair                            0xf193u
#define kIcon_wheelchair_alt                        0xf29bu
#define kIcon_wifi                                  0xf1ebu
#define kIcon_wikipedia_w                           0xf266u
#define kIcon_window_close                          0xf2d3u
#define kIcon_window_close_o                        0xf2d4u
#define kIcon_window_maximize                       0xf2d0u
#define kIcon_window_minimize                       0xf2d1u
#define kIcon_window_restore                        0xf2d2u
#define kIcon_windows                               0xf17au
#define kIcon_won                                   0xf159u
#define kIcon_wordpress                             0xf19au
#define kIcon_wpbeginner                            0xf297u
#define kIcon_wpexplorer                            0xf2deu
#define kIcon_wpforms                               0xf298u
#define kIcon_wrench                                0xf0adu
#define kIcon_xing                                  0xf168u
#define kIcon_xing_square                           0xf169u
#define kIcon_y_combinator                          0xf23bu
#define kIcon_y_combinator_square                   0xf1d4u
#define kIcon_yahoo                                 0xf19eu
#define kIcon_yc                                    0xf23bu
#define kIcon_yc_square                             0xf1d4u
#define kIcon_yelp                                  0xf1e9u
#define kIcon_yen                                   0xf157u
#define kIcon_yoast                                 0xf2b1u
#define kIcon_youtube                               0xf167u
#define kIcon_youtube_play                          0xf16au
#define kIcon_youtube_square                        0xf166u

#ifndef GUI_ButtonFA
#define GUI_ButtonFA GUI_ButtonFontAwesome
#endif

#ifndef FontAwesome
#define FontAwesome GUI_ButtonFontAwesome
#endif

class GUI_ButtonFontAwesome : public GUI_Label {
public:
    static GUI_ButtonFontAwesome* create(GUI_View *parent, Uint16 unicode, const char *label, int x, int y, int width = 0, int height = 0, SDL_Color color = cBlack, int align = GUI_ALIGN_CENTER | GUI_ALIGN_VCENTER, int fontSize = 2);

    virtual ~GUI_ButtonFontAwesome() override;
    virtual void draw() override;
    virtual bool handleEvents(SDL_Event *ev) override;
    void setActive(bool active);

    std::function<void(GUI_ButtonFontAwesome*)> action_cmd;

    SDL_Color bgColor;
    SDL_Color bgColor_hover;

    SDL_Color labelColor;
    SDL_Color labelColor_hover;
    SDL_Color labelColor_inactive;

    //SDL_Color iconColor;
    SDL_Color iconColor_hover;
    SDL_Color iconColor_inactive;

    // not for this class, just for get glyph as icon texture.
    static SDL_Texture* createTextureFormUnicode(Uint16 unicode, int* iWidth, int* iHeight, SDL_Color color = cBlack, int sizeIndex = 0);

    static SDL_Surface* createSurfaceFormUnicode(Uint16 unicode, int* iWidth, int* iHeight, SDL_Color color = cBlack, int sizeIndex = 0);

    static void Quit();

    bool isActive;
    bool isDown;

    GUI_ButtonFontAwesome(GUI_View *parent, Uint16 unicode, const char *label, int x, int y, int width, int height, SDL_Color color = cBlack, int align = GUI_ALIGN_CENTER | GUI_ALIGN_VCENTER, int fontSize = 2, std::function<void(GUI_ButtonFontAwesome*)> act_cmd = NULL);

private:
    //
    //bool isFocus;
};

#endif /* GUI_ButtonFontAwesome_hpp */
