#!/usr/bin/env bash

CWD=`pwd`

SCRIPT_PATH="$(realpath $( dirname ${BASH_SOURCE[0]} ))"
#echo "SCRIPT_PATH: \"$SCRIPT_PATH\""
#SERVER="$( dirname ${BASH_SOURCE[0]} )/server.js"

run="node server.js ../ -S -i false -p 44380"

#echo "exec $run"

cd $SCRIPT_PATH

exec $run $@

cd $CWD